# Generated by Django 6.0.3 on 2026-03-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escritura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('data_lavratura', models.DateField()),
                ('outorgante', models.CharField(max_length=200)),
                ('outorgado', models.CharField(max_length=200)),
                ('intermediador', models.CharField(max_length=200)),
                ('livro', models.CharField(max_length=50)),
                ('paginas', models.CharField(max_length=50)),
                ('valor_escritura', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_registro', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_certidao', models.DecimalField(decimal_places=2, max_digits=12)),
                ('telefone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
    ]
