# Generated by Django 6.0.3 on 2026-03-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrituras', '0002_escritura_andamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escritura',
            name='codigo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
