# Generated by Django 6.0.3 on 2026-03-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrituras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escritura',
            name='andamento',
            field=models.TextField(blank=True),
        ),
    ]
